import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const LANGUAGES = ['English', 'Hindi', 'Telugu', 'Tamil', 'Kannada']

export const TRANSLATIONS = {
  English: {
    // Brand
    app_name: 'Prayaas',
    app_tagline: 'Primary Referral and AI-based Screening for Assessing Oral Health',
    // Nav
    nav_dashboard: 'Dashboard',
    nav_screening: 'Screen Image',
    nav_settings: 'Settings',
    nav_about: 'About Us',
    nav_logout: 'Logout',
    nav_new_scan: '+ New Screening',
    nav_navigation: 'Navigation',
    // Dashboard
    dash_welcome: 'Welcome back',
    dash_summary: "Here's a summary of your screening activity",
    dash_refresh: 'Refresh',
    dash_total: 'Total Screenings',
    dash_total_sub: 'All time',
    dash_flagged: 'Flagged',
    dash_flagged_sub: 'Needs referral',
    dash_confidence: 'Avg Confidence',
    dash_confidence_sub: 'Across screenings',
    dash_last: 'Last Screening',
    dash_last_sub: 'Most recent',
    dash_recent: 'Recent Screenings',
    dash_new: '+ New Screening',
    dash_patient: 'Patient',
    dash_date: 'Date',
    dash_result: 'Result',
    dash_conf: 'Confidence',
    dash_none: 'No screenings yet.',
    dash_first: 'Screen your first image →',
    dash_cta_title: 'Ready to screen another image?',
    dash_cta_sub: 'Upload an oral cavity image and get a result in seconds',
    dash_cta_btn: 'Start Screening →',
    dash_clear: 'Clear',
    dash_referral: 'Referral',
    // Auth
    auth_welcome: 'Welcome back',
    auth_welcome_sub: 'Sign in to access oral cancer screening',
    auth_create: 'Create an account',
    auth_create_sub: 'Start screening oral images with AI',
    auth_full_name: 'Full Name',
    auth_email: 'Email Address',
    auth_password: 'Password',
    auth_confirm_password: 'Confirm Password',
    auth_signin: 'Sign In',
    auth_signup: 'Create Account',
    auth_processing: 'Processing…',
    auth_no_account: "Don't have an account?",
    auth_have_account: 'Already have an account?',
    auth_create_free: 'Create a free account',
    auth_signin_instead: 'Sign in instead',
    auth_pw_hint: 'Min. 8 characters, 1 uppercase, 1 number, 1 special character.',
    auth_pw_mismatch: 'Passwords do not match.',
    auth_created: 'Account created successfully! Please log in.',
    auth_terms: 'By continuing, you agree to our',
    auth_tos: 'Terms of Service',
    auth_privacy: 'Privacy Policy',
    auth_and: 'and',
    auth_feat_1: 'AI-powered oral cancer screening',
    auth_feat_2: 'Clinical-grade deep learning model',
    auth_feat_3: 'Instant 3-class risk assessment',
    auth_hero: 'Early oral cancer detection with AI',
    auth_hero_sub: 'Upload an oral cavity image and get a structured risk assessment in seconds.',
    // Screening
    screen_title: 'Oral Cancer Screening',
    screen_sub: 'Upload an oral cavity image · AI returns a 3-class assessment',
    screen_patient: 'Patient details',
    screen_image: 'Oral cavity image',
    screen_name: 'Name',
    screen_gender: 'Gender',
    screen_age: 'Age',
    screen_abha: 'ABHA ID',
    screen_select: 'Select…',
    screen_male: 'Male',
    screen_female: 'Female',
    screen_other: 'Other',
    screen_optional: 'Optional',
    screen_drop: 'Drop an image here',
    screen_browse: 'or click to browse — JPG or PNG',
    screen_analyze: 'Screen image',
    screen_analyzing: 'Screening…',
    screen_reset: 'Reset',
    screen_result: 'Screening result',
    screen_disclaimer: 'Screening aid only — not a diagnosis. Confirm findings with a clinician.',
    screen_processing: 'Processing breakdown',
    screen_download_report: 'Download report',
    screen_err_name: "Patient's name is required.",
    screen_err_gender: "Patient's gender is required.",
    screen_err_age: "Patient's age is required.",
    screen_err_image: 'Choose an image to screen.',
    // Settings
    settings_title: 'Settings',
    settings_sub: 'Manage your appearance and language preferences',
    settings_appear: 'Appearance',
    settings_appear_sub: 'Choose how Prayaas looks on this device',
    settings_lang: 'Language',
    settings_lang_sub: 'Select your preferred display language',
    settings_language: 'Language',
    settings_save: 'Save Changes',
    settings_saved: 'Saved!',
    settings_cur_theme: 'Current Theme',
    settings_acct: 'Account Settings',
    settings_lang_pending: 'Click "Save Changes" to apply',
    settings_across: 'across the whole app.',
    theme_light: 'Light',
    theme_dark: 'Dark',
    theme_neon: 'Neon',
    theme_light_desc: 'Clean white interface',
    theme_dark_desc: 'Easy on the eyes',
    theme_neon_desc: 'High-contrast vibrant',
    set_notif: 'Notifications',
    set_notif_sub: 'Email alerts, screening notifications',
    set_privacy: 'Privacy & Data',
    set_privacy_sub: 'Data collection and sharing settings',
    set_devices: 'Connected Devices',
    set_devices_sub: 'Manage sessions and logged-in devices',
    set_api: 'API Access',
    set_api_sub: 'View and manage your API key',
    // About
    about_title: 'Institute of Health Management Research',
    about_leadership: 'Leadership',
    about_team: 'Our Team',
    about_papers: 'Research Papers',
    about_mission: 'Our Web App',
    about_tech: 'Our Technology',
    about_open_pdf: 'Open PDF',
    about_publications: 'Publications',
    about_screened: 'Images Screened',
    about_accuracy: 'Model Accuracy',
    about_hospitals: 'Hospitals Served',
    // Logout
    logout_title: 'Log out?',
    logout_msg: 'You will be returned to the login screen.',
    logout_cancel: 'Cancel',
    logout_confirm: 'Yes, log out',
    // Common
    common_cancel: 'Cancel',
    common_done: 'Done',
    common_close: 'Close',
  },

  Hindi: {
    app_name: 'प्रयास',
    app_tagline: 'मौखिक स्वास्थ्य आकलन हेतु प्राथमिक रेफरल एवं AI-आधारित स्क्रीनिंग',
    nav_dashboard: 'डैशबोर्ड',
    dash_welcome: 'पुनः स्वागत है',
    dash_summary: 'यह आपकी स्क्रीनिंग गतिविधि का सारांश है',
    dash_refresh: 'रीफ़्रेश',
    dash_total: 'कुल स्क्रीनिंग',
    dash_total_sub: 'अब तक',
    dash_flagged: 'चिह्नित',
    dash_flagged_sub: 'रेफरल आवश्यक',
    dash_confidence: 'औसत विश्वास',
    dash_confidence_sub: 'सभी स्क्रीनिंग में',
    dash_last: 'अंतिम स्क्रीनिंग',
    dash_last_sub: 'सबसे हालिया',
    dash_recent: 'हालिया स्क्रीनिंग',
    dash_new: '+ नई स्क्रीनिंग',
    dash_patient: 'रोगी',
    dash_date: 'दिनांक',
    dash_result: 'परिणाम',
    dash_conf: 'विश्वास',
    dash_none: 'अभी तक कोई स्क्रीनिंग नहीं।',
    dash_first: 'अपनी पहली छवि स्क्रीन करें →',
    dash_cta_title: 'एक और छवि स्क्रीन करने के लिए तैयार?',
    dash_cta_sub: 'मौखिक गुहा की छवि अपलोड करें और सेकंडों में परिणाम पाएँ',
    dash_cta_btn: 'स्क्रीनिंग शुरू करें →',
    dash_clear: 'सामान्य',
    dash_referral: 'रेफरल',
    nav_screening: 'छवि स्क्रीन करें',
    nav_settings: 'सेटिंग्स',
    nav_about: 'हमारे बारे में',
    nav_logout: 'लॉग आउट',
    nav_new_scan: '+ नई स्क्रीनिंग',
    nav_navigation: 'नेविगेशन',
    auth_welcome: 'पुनः स्वागत है',
    auth_welcome_sub: 'मौखिक कैंसर स्क्रीनिंग हेतु साइन इन करें',
    auth_create: 'खाता बनाएँ',
    auth_create_sub: 'AI के साथ मौखिक छवियों की स्क्रीनिंग शुरू करें',
    auth_full_name: 'पूरा नाम',
    auth_email: 'ईमेल पता',
    auth_password: 'पासवर्ड',
    auth_confirm_password: 'पासवर्ड की पुष्टि करें',
    auth_signin: 'साइन इन',
    auth_signup: 'खाता बनाएँ',
    auth_processing: 'प्रक्रिया जारी…',
    auth_no_account: 'खाता नहीं है?',
    auth_have_account: 'पहले से खाता है?',
    auth_create_free: 'निःशुल्क खाता बनाएँ',
    auth_signin_instead: 'इसके बजाय साइन इन करें',
    auth_pw_hint: 'कम से कम 8 वर्ण, 1 बड़ा अक्षर, 1 अंक, 1 विशेष वर्ण।',
    auth_pw_mismatch: 'पासवर्ड मेल नहीं खाते।',
    auth_created: 'खाता सफलतापूर्वक बनाया गया! कृपया लॉग इन करें।',
    auth_terms: 'जारी रखकर, आप हमारी',
    auth_tos: 'सेवा शर्तों',
    auth_privacy: 'गोपनीयता नीति',
    auth_and: 'और',
    auth_feat_1: 'AI-आधारित मौखिक कैंसर स्क्रीनिंग',
    auth_feat_2: 'क्लिनिकल-ग्रेड डीप लर्निंग मॉडल',
    auth_feat_3: 'तत्काल 3-श्रेणी जोखिम आकलन',
    auth_hero: 'AI के साथ मौखिक कैंसर की प्रारंभिक पहचान',
    auth_hero_sub: 'मौखिक गुहा की छवि अपलोड करें और सेकंडों में संरचित जोखिम आकलन पाएँ।',
    screen_title: 'मौखिक कैंसर स्क्रीनिंग',
    screen_sub: 'मौखिक गुहा की छवि अपलोड करें · AI 3-श्रेणी आकलन देता है',
    screen_patient: 'रोगी विवरण',
    screen_image: 'मौखिक गुहा छवि',
    screen_name: 'नाम',
    screen_gender: 'लिंग',
    screen_age: 'आयु',
    screen_abha: 'ABHA आईडी',
    screen_select: 'चुनें…',
    screen_male: 'पुरुष',
    screen_female: 'महिला',
    screen_other: 'अन्य',
    screen_optional: 'वैकल्पिक',
    screen_drop: 'यहाँ छवि छोड़ें',
    screen_browse: 'या ब्राउज़ करने के लिए क्लिक करें — JPG या PNG',
    screen_analyze: 'छवि स्क्रीन करें',
    screen_analyzing: 'स्क्रीनिंग जारी…',
    screen_reset: 'रीसेट',
    screen_result: 'स्क्रीनिंग परिणाम',
    screen_disclaimer: 'केवल स्क्रीनिंग सहायता — निदान नहीं। चिकित्सक से पुष्टि करें।',
    screen_processing: 'प्रोसेसिंग विवरण',
    screen_download_report: 'रिपोर्ट डाउनलोड करें',
    screen_err_name: 'रोगी का नाम आवश्यक है।',
    screen_err_gender: 'रोगी का लिंग आवश्यक है।',
    screen_err_age: 'रोगी की आयु आवश्यक है।',
    screen_err_image: 'स्क्रीन करने हेतु छवि चुनें।',
    settings_title: 'सेटिंग्स',
    settings_sub: 'अपनी दिखावट और भाषा प्राथमिकताएँ प्रबंधित करें',
    settings_appear: 'दिखावट',
    settings_appear_sub: 'चुनें कि इस डिवाइस पर प्रयास कैसा दिखे',
    settings_lang: 'भाषा',
    settings_lang_sub: 'अपनी पसंदीदा प्रदर्शन भाषा चुनें',
    settings_language: 'भाषा',
    settings_save: 'परिवर्तन सहेजें',
    settings_saved: 'सहेजा गया!',
    settings_cur_theme: 'वर्तमान थीम',
    settings_acct: 'खाता सेटिंग्स',
    settings_lang_pending: 'लागू करने हेतु "परिवर्तन सहेजें" पर क्लिक करें',
    settings_across: 'पूरे ऐप में।',
    theme_light: 'लाइट',
    theme_dark: 'डार्क',
    theme_neon: 'नियॉन',
    theme_light_desc: 'स्वच्छ श्वेत इंटरफ़ेस',
    theme_dark_desc: 'आँखों के लिए आरामदायक',
    theme_neon_desc: 'उच्च-कंट्रास्ट जीवंत',
    set_notif: 'सूचनाएँ',
    set_notif_sub: 'ईमेल अलर्ट, स्क्रीनिंग सूचनाएँ',
    set_privacy: 'गोपनीयता एवं डेटा',
    set_privacy_sub: 'डेटा संग्रह एवं साझाकरण सेटिंग्स',
    set_devices: 'कनेक्टेड डिवाइस',
    set_devices_sub: 'सत्र एवं लॉग-इन डिवाइस प्रबंधित करें',
    set_api: 'API एक्सेस',
    set_api_sub: 'अपनी API कुंजी देखें एवं प्रबंधित करें',
    about_title: 'स्वास्थ्य प्रबंधन अनुसंधान संस्थान',
    about_leadership: 'नेतृत्व',
    about_team: 'हमारी टीम',
    about_papers: 'शोध पत्र',
    about_mission: 'हमारा वेब ऐप',
    about_tech: 'हमारी तकनीक',
    about_open_pdf: 'PDF खोलें',
    about_publications: 'प्रकाशन',
    about_screened: 'स्क्रीन की गई छवियाँ',
    about_accuracy: 'मॉडल सटीकता',
    about_hospitals: 'सेवित अस्पताल',
    logout_title: 'लॉग आउट करें?',
    logout_msg: 'आपको लॉगिन स्क्रीन पर लौटाया जाएगा।',
    logout_cancel: 'रद्द करें',
    logout_confirm: 'हाँ, लॉग आउट',
    common_cancel: 'रद्द करें',
    common_done: 'हो गया',
    common_close: 'बंद करें',
  },

  Telugu: {
    app_name: 'ప్రయాస్',
    app_tagline: 'నోటి ఆరోగ్య అంచనా కోసం ప్రాథమిక రెఫరల్ మరియు AI-ఆధారిత స్క్రీనింగ్',
    nav_dashboard: 'డాష్‌బోర్డ్',
    dash_welcome: 'తిరిగి స్వాగతం',
    dash_summary: 'మీ స్క్రీనింగ్ కార్యకలాపాల సారాంశం ఇది',
    dash_refresh: 'రిఫ్రెష్',
    dash_total: 'మొత్తం స్క్రీనింగ్‌లు',
    dash_total_sub: 'మొత్తం సమయం',
    dash_flagged: 'గుర్తించినవి',
    dash_flagged_sub: 'రెఫరల్ అవసరం',
    dash_confidence: 'సగటు విశ్వాసం',
    dash_confidence_sub: 'అన్ని స్క్రీనింగ్‌లలో',
    dash_last: 'చివరి స్క్రీనింగ్',
    dash_last_sub: 'అత్యంత ఇటీవలిది',
    dash_recent: 'ఇటీవలి స్క్రీనింగ్‌లు',
    dash_new: '+ కొత్త స్క్రీనింగ్',
    dash_patient: 'రోగి',
    dash_date: 'తేదీ',
    dash_result: 'ఫలితం',
    dash_conf: 'విశ్వాసం',
    dash_none: 'ఇంకా స్క్రీనింగ్‌లు లేవు.',
    dash_first: 'మీ మొదటి చిత్రాన్ని స్క్రీన్ చేయండి →',
    dash_cta_title: 'మరో చిత్రాన్ని స్క్రీన్ చేయడానికి సిద్ధమా?',
    dash_cta_sub: 'నోటి కుహర చిత్రాన్ని అప్‌లోడ్ చేసి సెకన్లలో ఫలితం పొందండి',
    dash_cta_btn: 'స్క్రీనింగ్ ప్రారంభించండి →',
    dash_clear: 'సాధారణం',
    dash_referral: 'రెఫరల్',
    nav_screening: 'చిత్రాన్ని స్క్రీన్ చేయండి',
    nav_settings: 'సెట్టింగ్‌లు',
    nav_about: 'మా గురించి',
    nav_logout: 'లాగ్ అవుట్',
    nav_new_scan: '+ కొత్త స్క్రీనింగ్',
    nav_navigation: 'నావిగేషన్',
    auth_welcome: 'తిరిగి స్వాగతం',
    auth_welcome_sub: 'నోటి క్యాన్సర్ స్క్రీనింగ్ కోసం సైన్ ఇన్ చేయండి',
    auth_create: 'ఖాతాను సృష్టించండి',
    auth_create_sub: 'AIతో నోటి చిత్రాల స్క్రీనింగ్ ప్రారంభించండి',
    auth_full_name: 'పూర్తి పేరు',
    auth_email: 'ఇమెయిల్ చిరునామా',
    auth_password: 'పాస్‌వర్డ్',
    auth_confirm_password: 'పాస్‌వర్డ్‌ను నిర్ధారించండి',
    auth_signin: 'సైన్ ఇన్',
    auth_signup: 'ఖాతా సృష్టించండి',
    auth_processing: 'ప్రాసెస్ అవుతోంది…',
    auth_no_account: 'ఖాతా లేదా?',
    auth_have_account: 'ఇప్పటికే ఖాతా ఉందా?',
    auth_create_free: 'ఉచిత ఖాతా సృష్టించండి',
    auth_signin_instead: 'బదులుగా సైన్ ఇన్ చేయండి',
    auth_pw_hint: 'కనీసం 8 అక్షరాలు, 1 పెద్ద అక్షరం, 1 సంఖ్య, 1 ప్రత్యేక అక్షరం.',
    auth_pw_mismatch: 'పాస్‌వర్డ్‌లు సరిపోలలేదు.',
    auth_created: 'ఖాతా విజయవంతంగా సృష్టించబడింది! దయచేసి లాగిన్ చేయండి.',
    auth_terms: 'కొనసాగించడం ద్వారా, మీరు మా',
    auth_tos: 'సేవా నిబంధనలు',
    auth_privacy: 'గోప్యతా విధానం',
    auth_and: 'మరియు',
    auth_feat_1: 'AI-ఆధారిత నోటి క్యాన్సర్ స్క్రీనింగ్',
    auth_feat_2: 'క్లినికల్-గ్రేడ్ డీప్ లెర్నింగ్ మోడల్',
    auth_feat_3: 'తక్షణ 3-తరగతి ప్రమాద అంచనా',
    auth_hero: 'AIతో నోటి క్యాన్సర్ ముందస్తు గుర్తింపు',
    auth_hero_sub: 'నోటి కుహర చిత్రాన్ని అప్‌లోడ్ చేసి సెకన్లలో నిర్మాణాత్మక ప్రమాద అంచనా పొందండి.',
    screen_title: 'నోటి క్యాన్సర్ స్క్రీనింగ్',
    screen_sub: 'నోటి కుహర చిత్రాన్ని అప్‌లోడ్ చేయండి · AI 3-తరగతి అంచనా ఇస్తుంది',
    screen_patient: 'రోగి వివరాలు',
    screen_image: 'నోటి కుహర చిత్రం',
    screen_name: 'పేరు',
    screen_gender: 'లింగం',
    screen_age: 'వయస్సు',
    screen_abha: 'ABHA ఐడీ',
    screen_select: 'ఎంచుకోండి…',
    screen_male: 'పురుషుడు',
    screen_female: 'స్త్రీ',
    screen_other: 'ఇతర',
    screen_optional: 'ఐచ్ఛికం',
    screen_drop: 'చిత్రాన్ని ఇక్కడ వదలండి',
    screen_browse: 'లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి — JPG లేదా PNG',
    screen_analyze: 'చిత్రాన్ని స్క్రీన్ చేయండి',
    screen_analyzing: 'స్క్రీనింగ్…',
    screen_reset: 'రీసెట్',
    screen_result: 'స్క్రీనింగ్ ఫలితం',
    screen_disclaimer: 'స్క్రీనింగ్ సహాయం మాత్రమే — నిర్ధారణ కాదు. వైద్యుడితో ధృవీకరించండి.',
    screen_processing: 'ప్రాసెసింగ్ వివరణ',
    screen_download_report: 'నివేదికను డౌన్‌లోడ్ చేయండి',
    screen_err_name: 'రోగి పేరు అవసరం.',
    screen_err_gender: 'రోగి లింగం అవసరం.',
    screen_err_age: 'రోగి వయస్సు అవసరం.',
    screen_err_image: 'స్క్రీన్ చేయడానికి చిత్రాన్ని ఎంచుకోండి.',
    settings_title: 'సెట్టింగ్‌లు',
    settings_sub: 'మీ రూపం మరియు భాషా ప్రాధాన్యతలను నిర్వహించండి',
    settings_appear: 'రూపం',
    settings_appear_sub: 'ఈ పరికరంలో ప్రయాస్ ఎలా కనిపించాలో ఎంచుకోండి',
    settings_lang: 'భాష',
    settings_lang_sub: 'మీకు నచ్చిన ప్రదర్శన భాషను ఎంచుకోండి',
    settings_language: 'భాష',
    settings_save: 'మార్పులను సేవ్ చేయండి',
    settings_saved: 'సేవ్ చేయబడింది!',
    settings_cur_theme: 'ప్రస్తుత థీమ్',
    settings_acct: 'ఖాతా సెట్టింగ్‌లు',
    settings_lang_pending: 'వర్తింపజేయడానికి "మార్పులను సేవ్ చేయండి" క్లిక్ చేయండి',
    settings_across: 'మొత్తం యాప్‌లో.',
    theme_light: 'లైట్',
    theme_dark: 'డార్క్',
    theme_neon: 'నియాన్',
    theme_light_desc: 'శుభ్రమైన తెల్ల ఇంటర్‌ఫేస్',
    theme_dark_desc: 'కళ్ళకు సౌకర్యవంతం',
    theme_neon_desc: 'హై-కాంట్రాస్ట్ శక్తివంతం',
    set_notif: 'నోటిఫికేషన్‌లు',
    set_notif_sub: 'ఇమెయిల్ హెచ్చరికలు, స్క్రీనింగ్ నోటిఫికేషన్‌లు',
    set_privacy: 'గోప్యత & డేటా',
    set_privacy_sub: 'డేటా సేకరణ మరియు భాగస్వామ్య సెట్టింగ్‌లు',
    set_devices: 'కనెక్ట్ చేసిన పరికరాలు',
    set_devices_sub: 'సెషన్‌లు మరియు లాగిన్ పరికరాలను నిర్వహించండి',
    set_api: 'API యాక్సెస్',
    set_api_sub: 'మీ API కీని చూడండి మరియు నిర్వహించండి',
    about_title: 'ఆరోగ్య నిర్వహణ పరిశోధన సంస్థ',
    about_leadership: 'నాయకత్వం',
    about_team: 'మా బృందం',
    about_papers: 'పరిశోధన పత్రాలు',
    about_mission: 'మా వెబ్ యాప్',
    about_tech: 'మా సాంకేతికత',
    about_open_pdf: 'PDF తెరవండి',
    about_publications: 'ప్రచురణలు',
    about_screened: 'స్క్రీన్ చేసిన చిత్రాలు',
    about_accuracy: 'మోడల్ ఖచ్చితత్వం',
    about_hospitals: 'సేవలందించిన ఆసుపత్రులు',
    logout_title: 'లాగ్ అవుట్ చేయాలా?',
    logout_msg: 'మిమ్మల్ని లాగిన్ స్క్రీన్‌కు తిరిగి పంపుతాము.',
    logout_cancel: 'రద్దు',
    logout_confirm: 'అవును, లాగ్ అవుట్',
    common_cancel: 'రద్దు',
    common_done: 'పూర్తయింది',
    common_close: 'మూసివేయి',
  },

  Tamil: {
    app_name: 'ப்ரயாஸ்',
    app_tagline: 'வாய் ஆரோக்கிய மதிப்பீட்டுக்கான முதன்மை பரிந்துரை மற்றும் AI-அடிப்படையிலான திரையிடல்',
    nav_dashboard: 'டாஷ்போர்டு',
    dash_welcome: 'மீண்டும் வரவேற்கிறோம்',
    dash_summary: 'உங்கள் திரையிடல் செயல்பாட்டின் சுருக்கம் இதோ',
    dash_refresh: 'புதுப்பி',
    dash_total: 'மொத்த திரையிடல்கள்',
    dash_total_sub: 'எல்லா நேரமும்',
    dash_flagged: 'குறியிடப்பட்டவை',
    dash_flagged_sub: 'பரிந்துரை தேவை',
    dash_confidence: 'சராசரி நம்பிக்கை',
    dash_confidence_sub: 'அனைத்து திரையிடல்களிலும்',
    dash_last: 'கடைசி திரையிடல்',
    dash_last_sub: 'மிக சமீபத்தியது',
    dash_recent: 'சமீபத்திய திரையிடல்கள்',
    dash_new: '+ புதிய திரையிடல்',
    dash_patient: 'நோயாளி',
    dash_date: 'தேதி',
    dash_result: 'முடிவு',
    dash_conf: 'நம்பிக்கை',
    dash_none: 'இதுவரை திரையிடல்கள் இல்லை.',
    dash_first: 'உங்கள் முதல் படத்தை திரையிடுங்கள் →',
    dash_cta_title: 'மற்றொரு படத்தை திரையிட தயாரா?',
    dash_cta_sub: 'வாய் குழி படத்தைப் பதிவேற்றி வினாடிகளில் முடிவைப் பெறுங்கள்',
    dash_cta_btn: 'திரையிடலைத் தொடங்கு →',
    dash_clear: 'இயல்பானது',
    dash_referral: 'பரிந்துரை',
    nav_screening: 'படத்தை திரையிடு',
    nav_settings: 'அமைப்புகள்',
    nav_about: 'எங்களைப் பற்றி',
    nav_logout: 'வெளியேறு',
    nav_new_scan: '+ புதிய திரையிடல்',
    nav_navigation: 'வழிசெலுத்தல்',
    auth_welcome: 'மீண்டும் வரவேற்கிறோம்',
    auth_welcome_sub: 'வாய் புற்றுநோய் திரையிடலுக்கு உள்நுழையவும்',
    auth_create: 'கணக்கை உருவாக்கு',
    auth_create_sub: 'AI மூலம் வாய் படங்களை திரையிடத் தொடங்குங்கள்',
    auth_full_name: 'முழு பெயர்',
    auth_email: 'மின்னஞ்சல் முகவரி',
    auth_password: 'கடவுச்சொல்',
    auth_confirm_password: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    auth_signin: 'உள்நுழை',
    auth_signup: 'கணக்கை உருவாக்கு',
    auth_processing: 'செயலாக்கம்…',
    auth_no_account: 'கணக்கு இல்லையா?',
    auth_have_account: 'ஏற்கனவே கணக்கு உள்ளதா?',
    auth_create_free: 'இலவச கணக்கை உருவாக்கு',
    auth_signin_instead: 'மாறாக உள்நுழையவும்',
    auth_pw_hint: 'குறைந்தது 8 எழுத்துகள், 1 பெரிய எழுத்து, 1 எண், 1 சிறப்பு எழுத்து.',
    auth_pw_mismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை.',
    auth_created: 'கணக்கு வெற்றிகரமாக உருவாக்கப்பட்டது! உள்நுழையவும்.',
    auth_terms: 'தொடர்வதன் மூலம், நீங்கள் எங்கள்',
    auth_tos: 'சேவை விதிமுறைகள்',
    auth_privacy: 'தனியுரிமைக் கொள்கை',
    auth_and: 'மற்றும்',
    auth_feat_1: 'AI-அடிப்படையிலான வாய் புற்றுநோய் திரையிடல்',
    auth_feat_2: 'மருத்துவ-தர ஆழ்ந்த கற்றல் மாதிரி',
    auth_feat_3: 'உடனடி 3-வகை ஆபத்து மதிப்பீடு',
    auth_hero: 'AI மூலம் வாய் புற்றுநோயை முன்கூட்டியே கண்டறிதல்',
    auth_hero_sub: 'வாய் குழி படத்தைப் பதிவேற்றி வினாடிகளில் கட்டமைக்கப்பட்ட ஆபத்து மதிப்பீட்டைப் பெறுங்கள்.',
    screen_title: 'வாய் புற்றுநோய் திரையிடல்',
    screen_sub: 'வாய் குழி படத்தைப் பதிவேற்றவும் · AI 3-வகை மதிப்பீட்டை வழங்கும்',
    screen_patient: 'நோயாளி விவரங்கள்',
    screen_image: 'வாய் குழி படம்',
    screen_name: 'பெயர்',
    screen_gender: 'பாலினம்',
    screen_age: 'வயது',
    screen_abha: 'ABHA அடையாள எண்',
    screen_select: 'தேர்ந்தெடு…',
    screen_male: 'ஆண்',
    screen_female: 'பெண்',
    screen_other: 'மற்றவை',
    screen_optional: 'விருப்பமானது',
    screen_drop: 'படத்தை இங்கே இடவும்',
    screen_browse: 'அல்லது உலாவ கிளிக் செய்யவும் — JPG அல்லது PNG',
    screen_analyze: 'படத்தை திரையிடு',
    screen_analyzing: 'திரையிடுகிறது…',
    screen_reset: 'மீட்டமை',
    screen_result: 'திரையிடல் முடிவு',
    screen_disclaimer: 'திரையிடல் உதவி மட்டுமே — நோயறிதல் அல்ல. மருத்துவரிடம் உறுதிப்படுத்தவும்.',
    screen_processing: 'செயலாக்க விவரம்',
    screen_download_report: 'அறிக்கையைப் பதிவிறக்கு',
    screen_err_name: 'நோயாளியின் பெயர் தேவை.',
    screen_err_gender: 'நோயாளியின் பாலினம் தேவை.',
    screen_err_age: 'நோயாளியின் வயது தேவை.',
    screen_err_image: 'திரையிட ஒரு படத்தைத் தேர்ந்தெடுக்கவும்.',
    settings_title: 'அமைப்புகள்',
    settings_sub: 'உங்கள் தோற்றம் மற்றும் மொழி விருப்பங்களை நிர்வகிக்கவும்',
    settings_appear: 'தோற்றம்',
    settings_appear_sub: 'இந்த சாதனத்தில் ப்ரயாஸ் எப்படித் தோன்ற வேண்டும் என்பதைத் தேர்வுசெய்க',
    settings_lang: 'மொழி',
    settings_lang_sub: 'உங்கள் விருப்ப காட்சி மொழியைத் தேர்ந்தெடுக்கவும்',
    settings_language: 'மொழி',
    settings_save: 'மாற்றங்களைச் சேமி',
    settings_saved: 'சேமிக்கப்பட்டது!',
    settings_cur_theme: 'தற்போதைய தீம்',
    settings_acct: 'கணக்கு அமைப்புகள்',
    settings_lang_pending: 'பயன்படுத்த "மாற்றங்களைச் சேமி" கிளிக் செய்யவும்',
    settings_across: 'முழு பயன்பாட்டிலும்.',
    theme_light: 'லைட்',
    theme_dark: 'டார்க்',
    theme_neon: 'நியான்',
    theme_light_desc: 'சுத்தமான வெள்ளை இடைமுகம்',
    theme_dark_desc: 'கண்களுக்கு எளிதானது',
    theme_neon_desc: 'உயர்-மாறுபாடு துடிப்பானது',
    set_notif: 'அறிவிப்புகள்',
    set_notif_sub: 'மின்னஞ்சல் எச்சரிக்கைகள், திரையிடல் அறிவிப்புகள்',
    set_privacy: 'தனியுரிமை & தரவு',
    set_privacy_sub: 'தரவு சேகரிப்பு மற்றும் பகிர்வு அமைப்புகள்',
    set_devices: 'இணைக்கப்பட்ட சாதனங்கள்',
    set_devices_sub: 'அமர்வுகள் மற்றும் உள்நுழைந்த சாதனங்களை நிர்வகிக்கவும்',
    set_api: 'API அணுகல்',
    set_api_sub: 'உங்கள் API விசையைக் காண்க மற்றும் நிர்வகிக்கவும்',
    about_title: 'சுகாதார மேலாண்மை ஆராய்ச்சி நிறுவனம்',
    about_leadership: 'தலைமை',
    about_team: 'எங்கள் குழு',
    about_papers: 'ஆராய்ச்சிக் கட்டுரைகள்',
    about_mission: 'எங்கள் வலை பயன்பாடு',
    about_tech: 'எங்கள் தொழில்நுட்பம்',
    about_open_pdf: 'PDF திற',
    about_publications: 'வெளியீடுகள்',
    about_screened: 'திரையிடப்பட்ட படங்கள்',
    about_accuracy: 'மாதிரி துல்லியம்',
    about_hospitals: 'சேவை செய்யப்பட்ட மருத்துவமனைகள்',
    logout_title: 'வெளியேற வேண்டுமா?',
    logout_msg: 'நீங்கள் உள்நுழைவுத் திரைக்குத் திருப்பி அனுப்பப்படுவீர்கள்.',
    logout_cancel: 'ரத்து',
    logout_confirm: 'ஆம், வெளியேறு',
    common_cancel: 'ரத்து',
    common_done: 'முடிந்தது',
    common_close: 'மூடு',
  },

  Kannada: {
    app_name: 'ಪ್ರಯಾಸ್',
    app_tagline: 'ಬಾಯಿ ಆರೋಗ್ಯ ಮೌಲ್ಯಮಾಪನಕ್ಕಾಗಿ ಪ್ರಾಥಮಿಕ ಶಿಫಾರಸು ಮತ್ತು AI-ಆಧಾರಿತ ಸ್ಕ್ರೀನಿಂಗ್',
    nav_dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    dash_welcome: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    dash_summary: 'ನಿಮ್ಮ ಸ್ಕ್ರೀನಿಂಗ್ ಚಟುವಟಿಕೆಯ ಸಾರಾಂಶ ಇಲ್ಲಿದೆ',
    dash_refresh: 'ರಿಫ್ರೆಶ್',
    dash_total: 'ಒಟ್ಟು ಸ್ಕ್ರೀನಿಂಗ್‌ಗಳು',
    dash_total_sub: 'ಎಲ್ಲಾ ಸಮಯ',
    dash_flagged: 'ಗುರುತಿಸಲಾದವು',
    dash_flagged_sub: 'ಶಿಫಾರಸು ಅಗತ್ಯ',
    dash_confidence: 'ಸರಾಸರಿ ವಿಶ್ವಾಸ',
    dash_confidence_sub: 'ಎಲ್ಲಾ ಸ್ಕ್ರೀನಿಂಗ್‌ಗಳಲ್ಲಿ',
    dash_last: 'ಕೊನೆಯ ಸ್ಕ್ರೀನಿಂಗ್',
    dash_last_sub: 'ಇತ್ತೀಚಿನದು',
    dash_recent: 'ಇತ್ತೀಚಿನ ಸ್ಕ್ರೀನಿಂಗ್‌ಗಳು',
    dash_new: '+ ಹೊಸ ಸ್ಕ್ರೀನಿಂಗ್',
    dash_patient: 'ರೋಗಿ',
    dash_date: 'ದಿನಾಂಕ',
    dash_result: 'ಫಲಿತಾಂಶ',
    dash_conf: 'ವಿಶ್ವಾಸ',
    dash_none: 'ಇನ್ನೂ ಯಾವುದೇ ಸ್ಕ್ರೀನಿಂಗ್ ಇಲ್ಲ.',
    dash_first: 'ನಿಮ್ಮ ಮೊದಲ ಚಿತ್ರವನ್ನು ಸ್ಕ್ರೀನ್ ಮಾಡಿ →',
    dash_cta_title: 'ಇನ್ನೊಂದು ಚಿತ್ರವನ್ನು ಸ್ಕ್ರೀನ್ ಮಾಡಲು ಸಿದ್ಧರಿದ್ದೀರಾ?',
    dash_cta_sub: 'ಬಾಯಿ ಕುಹರದ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಫಲಿತಾಂಶ ಪಡೆಯಿರಿ',
    dash_cta_btn: 'ಸ್ಕ್ರೀನಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ →',
    dash_clear: 'ಸಾಮಾನ್ಯ',
    dash_referral: 'ಶಿಫಾರಸು',
    nav_screening: 'ಚಿತ್ರವನ್ನು ಸ್ಕ್ರೀನ್ ಮಾಡಿ',
    nav_settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    nav_about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    nav_logout: 'ಲಾಗ್ ಔಟ್',
    nav_new_scan: '+ ಹೊಸ ಸ್ಕ್ರೀನಿಂಗ್',
    nav_navigation: 'ನ್ಯಾವಿಗೇಶನ್',
    auth_welcome: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    auth_welcome_sub: 'ಬಾಯಿ ಕ್ಯಾನ್ಸರ್ ಸ್ಕ್ರೀನಿಂಗ್‌ಗಾಗಿ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    auth_create: 'ಖಾತೆ ರಚಿಸಿ',
    auth_create_sub: 'AI ಮೂಲಕ ಬಾಯಿ ಚಿತ್ರಗಳ ಸ್ಕ್ರೀನಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ',
    auth_full_name: 'ಪೂರ್ಣ ಹೆಸರು',
    auth_email: 'ಇಮೇಲ್ ವಿಳಾಸ',
    auth_password: 'ಪಾಸ್‌ವರ್ಡ್',
    auth_confirm_password: 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    auth_signin: 'ಸೈನ್ ಇನ್',
    auth_signup: 'ಖಾತೆ ರಚಿಸಿ',
    auth_processing: 'ಪ್ರಕ್ರಿಯೆ ನಡೆಯುತ್ತಿದೆ…',
    auth_no_account: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    auth_have_account: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    auth_create_free: 'ಉಚಿತ ಖಾತೆ ರಚಿಸಿ',
    auth_signin_instead: 'ಬದಲಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    auth_pw_hint: 'ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು, 1 ದೊಡ್ಡ ಅಕ್ಷರ, 1 ಸಂಖ್ಯೆ, 1 ವಿಶೇಷ ಅಕ್ಷರ.',
    auth_pw_mismatch: 'ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ.',
    auth_created: 'ಖಾತೆ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ! ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ.',
    auth_terms: 'ಮುಂದುವರಿಯುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ',
    auth_tos: 'ಸೇವಾ ನಿಯಮಗಳು',
    auth_privacy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    auth_and: 'ಮತ್ತು',
    auth_feat_1: 'AI-ಆಧಾರಿತ ಬಾಯಿ ಕ್ಯಾನ್ಸರ್ ಸ್ಕ್ರೀನಿಂಗ್',
    auth_feat_2: 'ಕ್ಲಿನಿಕಲ್-ಗ್ರೇಡ್ ಡೀಪ್ ಲರ್ನಿಂಗ್ ಮಾದರಿ',
    auth_feat_3: 'ತಕ್ಷಣದ 3-ವರ್ಗ ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ',
    auth_hero: 'AI ಮೂಲಕ ಬಾಯಿ ಕ್ಯಾನ್ಸರ್‌ನ ಆರಂಭಿಕ ಪತ್ತೆ',
    auth_hero_sub: 'ಬಾಯಿ ಕುಹರದ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಸೆಕೆಂಡುಗಳಲ್ಲಿ ರಚನಾತ್ಮಕ ಅಪಾಯ ಮೌಲ್ಯಮಾಪನ ಪಡೆಯಿರಿ.',
    screen_title: 'ಬಾಯಿ ಕ್ಯಾನ್ಸರ್ ಸ್ಕ್ರೀನಿಂಗ್',
    screen_sub: 'ಬಾಯಿ ಕುಹರದ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ · AI 3-ವರ್ಗ ಮೌಲ್ಯಮಾಪನ ನೀಡುತ್ತದೆ',
    screen_patient: 'ರೋಗಿಯ ವಿವರಗಳು',
    screen_image: 'ಬಾಯಿ ಕುಹರದ ಚಿತ್ರ',
    screen_name: 'ಹೆಸರು',
    screen_gender: 'ಲಿಂಗ',
    screen_age: 'ವಯಸ್ಸು',
    screen_abha: 'ABHA ಐಡಿ',
    screen_select: 'ಆಯ್ಕೆಮಾಡಿ…',
    screen_male: 'ಪುರುಷ',
    screen_female: 'ಮಹಿಳೆ',
    screen_other: 'ಇತರೆ',
    screen_optional: 'ಐಚ್ಛಿಕ',
    screen_drop: 'ಚಿತ್ರವನ್ನು ಇಲ್ಲಿ ಬಿಡಿ',
    screen_browse: 'ಅಥವಾ ಬ್ರೌಸ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ — JPG ಅಥವಾ PNG',
    screen_analyze: 'ಚಿತ್ರವನ್ನು ಸ್ಕ್ರೀನ್ ಮಾಡಿ',
    screen_analyzing: 'ಸ್ಕ್ರೀನಿಂಗ್…',
    screen_reset: 'ಮರುಹೊಂದಿಸಿ',
    screen_result: 'ಸ್ಕ್ರೀನಿಂಗ್ ಫಲಿತಾಂಶ',
    screen_disclaimer: 'ಸ್ಕ್ರೀನಿಂಗ್ ಸಹಾಯ ಮಾತ್ರ — ರೋಗನಿರ್ಣಯವಲ್ಲ. ವೈದ್ಯರೊಂದಿಗೆ ಖಚಿತಪಡಿಸಿ.',
    screen_processing: 'ಪ್ರಕ್ರಿಯೆ ವಿವರ',
    screen_download_report: 'ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    screen_err_name: 'ರೋಗಿಯ ಹೆಸರು ಅಗತ್ಯವಿದೆ.',
    screen_err_gender: 'ರೋಗಿಯ ಲಿಂಗ ಅಗತ್ಯವಿದೆ.',
    screen_err_age: 'ರೋಗಿಯ ವಯಸ್ಸು ಅಗತ್ಯವಿದೆ.',
    screen_err_image: 'ಸ್ಕ್ರೀನ್ ಮಾಡಲು ಚಿತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    settings_title: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    settings_sub: 'ನಿಮ್ಮ ನೋಟ ಮತ್ತು ಭಾಷಾ ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    settings_appear: 'ನೋಟ',
    settings_appear_sub: 'ಈ ಸಾಧನದಲ್ಲಿ ಪ್ರಯಾಸ್ ಹೇಗೆ ಕಾಣಬೇಕೆಂದು ಆಯ್ಕೆಮಾಡಿ',
    settings_lang: 'ಭಾಷೆ',
    settings_lang_sub: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಪ್ರದರ್ಶನ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    settings_language: 'ಭಾಷೆ',
    settings_save: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    settings_saved: 'ಉಳಿಸಲಾಗಿದೆ!',
    settings_cur_theme: 'ಪ್ರಸ್ತುತ ಥೀಮ್',
    settings_acct: 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    settings_lang_pending: 'ಅನ್ವಯಿಸಲು "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ" ಕ್ಲಿಕ್ ಮಾಡಿ',
    settings_across: 'ಸಂಪೂರ್ಣ ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ.',
    theme_light: 'ಲೈಟ್',
    theme_dark: 'ಡಾರ್ಕ್',
    theme_neon: 'ನಿಯಾನ್',
    theme_light_desc: 'ಸ್ವಚ್ಛ ಬಿಳಿ ಇಂಟರ್‌ಫೇಸ್',
    theme_dark_desc: 'ಕಣ್ಣುಗಳಿಗೆ ಸುಲಭ',
    theme_neon_desc: 'ಹೈ-ಕಾಂಟ್ರಾಸ್ಟ್ ವೈಬ್ರಂಟ್',
    set_notif: 'ಅಧಿಸೂಚನೆಗಳು',
    set_notif_sub: 'ಇಮೇಲ್ ಎಚ್ಚರಿಕೆಗಳು, ಸ್ಕ್ರೀನಿಂಗ್ ಅಧಿಸೂಚನೆಗಳು',
    set_privacy: 'ಗೌಪ್ಯತೆ ಮತ್ತು ಡೇಟಾ',
    set_privacy_sub: 'ಡೇಟಾ ಸಂಗ್ರಹಣೆ ಮತ್ತು ಹಂಚಿಕೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    set_devices: 'ಸಂಪರ್ಕಿತ ಸಾಧನಗಳು',
    set_devices_sub: 'ಸೆಷನ್‌ಗಳು ಮತ್ತು ಲಾಗಿನ್ ಸಾಧನಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    set_api: 'API ಪ್ರವೇಶ',
    set_api_sub: 'ನಿಮ್ಮ API ಕೀಲಿಯನ್ನು ವೀಕ್ಷಿಸಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ',
    about_title: 'ಆರೋಗ್ಯ ನಿರ್ವಹಣಾ ಸಂಶೋಧನಾ ಸಂಸ್ಥೆ',
    about_leadership: 'ನಾಯಕತ್ವ',
    about_team: 'ನಮ್ಮ ತಂಡ',
    about_papers: 'ಸಂಶೋಧನಾ ಪ್ರಬಂಧಗಳು',
    about_mission: 'ನಮ್ಮ ವೆಬ್ ಅಪ್ಲಿಕೇಶನ್',
    about_tech: 'ನಮ್ಮ ತಂತ್ರಜ್ಞಾನ',
    about_open_pdf: 'PDF ತೆರೆಯಿರಿ',
    about_publications: 'ಪ್ರಕಟಣೆಗಳು',
    about_screened: 'ಸ್ಕ್ರೀನ್ ಮಾಡಿದ ಚಿತ್ರಗಳು',
    about_accuracy: 'ಮಾದರಿ ನಿಖರತೆ',
    about_hospitals: 'ಸೇವೆ ಸಲ್ಲಿಸಿದ ಆಸ್ಪತ್ರೆಗಳು',
    logout_title: 'ಲಾಗ್ ಔಟ್ ಮಾಡುವಿರಾ?',
    logout_msg: 'ನಿಮ್ಮನ್ನು ಲಾಗಿನ್ ಪರದೆಗೆ ಹಿಂದಿರುಗಿಸಲಾಗುತ್ತದೆ.',
    logout_cancel: 'ರದ್ದು',
    logout_confirm: 'ಹೌದು, ಲಾಗ್ ಔಟ್',
    common_cancel: 'ರದ್ದು',
    common_done: 'ಮುಗಿದಿದೆ',
    common_close: 'ಮುಚ್ಚಿ',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem('prayaas-language') || 'English',
  )

  const t = (key) => TRANSLATIONS[language]?.[key] ?? TRANSLATIONS.English[key] ?? key

  const changeLanguage = (lang) => {
    setLanguage(lang)
    localStorage.setItem('prayaas-language', lang)
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
